// Generated by https://quicktype.io

export interface LoginData {
  username: string;
  password: string;
  date:     Date | null | undefined;
}

export interface LoginResponse {
  ok:    boolean;
  user:  UserLogin;
  token: string;
}

export interface UserLogin {
  id:       number;
  username: string;
}