// Generated by https://quicktype.io

export interface LoginData {
  username: string;
  password: string,
}

export interface LoginResponse {
  ok:    boolean;
  user:  User;
  token: string;
}

export interface User {
  id:       number;
  username: string;
}