// Generated by https://quicktype.io

export interface EmployeeResponse {
    ok:    boolean;
    data:  Employee[];
    page:  number;
    count: number;
    size:  number;
}

export interface Employee {
    id:              number;
    name:            string;
    first_lastname:  string;
    second_lastname: string;
    gender:          string;
    email:           string;
    created_at:      string;
    updated_at:      string;
}

// Generated by https://quicktype.io


// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface UpdateEmployeeData {
    name:            string;
    first_lastname:  string;
    second_lastname: string;
    gender:          string;
    email:           string;
    
}

export interface UpdatePasswordData{
    current_Password: string;
    new_Password: string;
    confirmationNew_Password: string;
}
// Generated by https://quicktype.io

export interface UpdateEmployeeResponse{
    ok:   boolean;
    data: UpdateResponse;
}

export interface UpdateResponse {
    id:              number;
    name:            string;
    first_lastname:  string;
    second_lastname: string;
    gender:          string;
    email:           string;
    created_at:      string;
    updated_at:      string;
}// Generated by https://quicktype.io

export interface UpdateResponsePassword {
    ok:   boolean;
    data: Data;
}

export interface Data {
    id:         number;
    username:   string;
    password:   string;
    updated_at: string;
}


