export interface CommissionFormData {
	initDate : Date | null | undefined;
	finalDate: Date | null | undefined;
};

export interface SalesState {
	loadingCommissions: boolean
	waterCommissions:  	Commission[];
	icebarCommissions: 	Commission[];
	icecubeCommissions: Commission[];
}

// Generated by https://quicktype.io
export interface CommissionResponse {
	ok:                  boolean;
	water_commissions: 	 Commission[];
	icebar_commissions:  Commission[];
	icecube_commissions: Commission[];
}

export interface Commission {
	employee:   string;
	commission: number;
	branch:     string;
}

export interface TopProductsResponse {
	ok:           boolean;
	by_frequency: TopProduct[];
	by_money:     TopProduct[];
}

interface TopProduct {
	frequency: number;
	money:     number;
	product:   string;
}
