export interface CommissionFormData {
	initDate : Date | null | undefined;
	finalDate: Date | null | undefined;
};

export interface SalesState {
	
}

// Generated by https://quicktype.io
export interface CommissionResponse {
	ok:                boolean;
	water_commissions: WaterCommission[];
}

export interface WaterCommission {
	employee:   string;
	commission: number;
	branch:     string;
}