export interface CommissionFormData {
	initDate : Date | null | undefined;
	finalDate: Date | null | undefined;
};

export interface SalesState {
	loadingCommissions: boolean
	waterCommissions:  	WaterCommission[];
	icebarCommissions: 	IceBarCommission[];
	icecubeCommissions: IceCubeCommission[];
}

// Generated by https://quicktype.io
export interface CommissionResponse {
	ok:                  boolean;
	water_commissions: 	 WaterCommission[];
	icebar_commissions:  IceBarCommission[];
	icecube_commissions: IceCubeCommission[];
}

export interface WaterCommission {
	employee:   string;
	commission: number;
	branch:     string;
}

export interface IceBarCommission {
	employee:   string;
	commission: number;
	branch:     string;
}

export interface IceCubeCommission {
	employee:   string;
	commission: number;
	branch:     string;
}